import { type Metadata } from 'next';
import ConvexClerkProvider from '@/components/ui/providers/ConvexClerkProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Browser Webcam',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ConvexClerkProvider>
  );
}
